### ISSUE TITLE
Can't write above current viewport

### ISSUE THREAD

**Issue by rstacruz** [dylang/observatory#11]
observatory can't edit lines that are outside the viewport. it uses  `require('ansi-escapes').cursorUp(20)`, which doesn't go above whatever's currently visible. instead, consider using `process.stdout.moveCursor(0, -20)`.

Notice in this screencast below that the first line keeps on changing. Also, when I scroll up after its done, the items that should be green are left not-green.

![observatory-problem](https://cloud.githubusercontent.com/assets/74385/12669550/783a7bfa-c69c-11e5-928c-df4544596e92.gif)

**Comment by rstacruz** [comment]
aw damn, .moveCursor suffers the same problem. Unless there's another workaround, I don't think this can be fixed.

**Comment by dylang** [comment]
I believe this is a limitation of the terminal technology, which I feel like was once printed right to paper before it was common for computers to have screens. 

Alternate solution:
I've thought about having npm-check a browser window for better feedback and interactions and interactions not possible in the terminal, such as hovering over a node module's name to learn more about it. The client would use something like koa or express and there's a node module for opening a page in the default browser. The idea is inspired by this project: https://github.com/shurcooL/Go-Package-Store
